# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|

if Vagrant.has_plugin? "vagrant-vbguest"
config.vbguest.no_install = true
config.vbguest.auto_update = false
config.vbguest.no_remote = true
end
config.vm.define :ubuntuHaproxy do |ubuntuHaproxy|
ubuntuHaproxy.vm.box = "bento/ubuntu-20.04"
ubuntuHaproxy.vm.network :private_network, ip: "192.168.100.2"
ubuntuHaproxy.vm.hostname = "ubuntuHaproxy"
end
config.vm.define :ubuntuWeb1 do |ubuntuWeb1|
ubuntuWeb1.vm.box = "bento/ubuntu-20.04"
ubuntuWeb1.vm.network :private_network, ip: "192.168.100.3"
ubuntuWeb1.vm.hostname = "ubuntuWeb1"
end
config.vm.define :ubuntuWeb2 do |ubuntuWeb2|
ubuntuWeb2.vm.box = "bento/ubuntu-20.04"
ubuntuWeb2.vm.network :private_network, ip: "192.168.100.4"
ubuntuWeb2.vm.hostname = "ubuntuWeb2"
end
config.vm.define :ubuntuWeb3 do |ubuntuWeb3|
ubuntuWeb3.vm.box = "bento/ubuntu-20.04"
ubuntuWeb3.vm.network :private_network, ip: "192.168.100.5"
ubuntuWeb3.vm.hostname = "ubuntuWeb3"
end
end